tag creation verification check added

diff --git a/gh-skeleton b/gh-skeleton
--- a/gh-skeleton
+++ b/gh-skeleton
@@ -134,6 +134,14 @@ clone_repo() {
   log_info "creating initial version tag v0.0.1"
   git tag v0.0.1
 
+  log_info "Verifying tag creation:"
+  if git tag | grep -q "v0.0.1"; then
+    log_ok "Tag v.0.0.1 created successfully."
+  else
+    log_error "Tag creation failed."
+    return
+  fi
+
   log_info "Creating the lineage.yml file."
   cat << END_OF_LINE > .github/lineage.yml
 ---
@@ -174,8 +182,13 @@ END_OF_LINE
       log_info "The remote repository ${dest_org}/${dest_repo} already existed."
       ;;&
     created | exists)
-      log_info "Pushing ${DEFAULT_BRANCH} and first-commit branches to the remote."
-      git push origin "${DEFAULT_BRANCH}" first-commits v0.0.1 --set-upstream
+      log_info "Pushing ${DEFAULT_BRANCH}, first-commits, and tag v0.0.1 to the remote."
+      git push origin "${DEFAULT_BRANCH}" --set-upstream
+      git push origin first-commits --set-upstream
+      if ! git push origin v0.0.1; then
+        log_error "Failed to push tag v0.0.1."
+      fi
+      
       log_info "Opening a new pull request for the first-commits branch."
       gh pr create --title "First commits" --assignee=@me --web
       ;;
